version: '3'
services:
  juice-shop:
    image: marvol0/juice-shop
    container_name: juice-shop
    ports:
      - "3000:3000"
  
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - db
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volume:
      - ./sonarqube:/opt/sonarqube/conf
    ports:
      - "9000:9000"
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins/jobs:/var/jenkins_home/jobs
    ports: 
      - "8080:8080"
  
  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    environment:
      - ZAP_PORT=8090
    ports:
      - "8090:8090"
    volumes:
      - ./zap/zap_config.xml:/home/zap/.ZAP/config.xml
      - ./zap/reports:/zap/reports